highligter: pygments
mardown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
